<?php


 $title = 'Add new Replacement';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('replace', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('wordone'));
 echo $this->formRow($form->get('wordtwo'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();