<?php


 $title = 'Text to Replace';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('replace', array('action' => 'text')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formRow($form->get('text'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 
 
 ?>
 <?php
  if(isset($text)){?>
  <h3>Ersetzte Nachricht:</h3>
 <h2><?php echo $this->escapeHtml($text->textRepl);?></h2>
 
 <h3>----------------------------------------------------------------</h3>
 <h3>Original Nachricht:</h3>
 <h2><?php echo $this->escapeHtml($text->text);?></h2>
 <?php
  }
 ?>